spring:
  redis:
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: -1
    cluster:
      nodes:
        - 192.168.50.133:6379
        - 192.168.50.133:6380
        - 192.168.50.133:6381
        - 192.168.50.109:6379
        - 192.168.50.109:6380
        - 192.168.50.109:6381
    timeout: 6000ms
  application:
    name: redis-cluster-test
  datasource:
      hikari:
        auto-commit: true
        connection-timeout: 20000
        driver-class-name: org.mariadb.jdbc.Driver
        max-lifetime: 0
        maximum-pool-size: 1000
        minimum-idle: 0
      password: a22607226
      url: jdbc:mariadb://localhost:3306/ry
      username: root
  jpa:
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
    show-sql: true
server:
  port: 8443
