spring:
  redis:
    host: node1
    username: Test
    database: 0
    timeout: 6000ms
    port: 6379
  application:
    name: redis-cluster-test
server:
  port: 8080

redis:
  read-only:
    port: 6379
    host: node2
